# Generated by Django 4.1.5 on 2023-01-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_data_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='diagnosis',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'osmotic diuresis'), (1, 'fluid overload'), (2, 'diabetes insipidus'), (3, 'adipsic diabetes insipidus'), (4, 'healthy')]),
        ),
    ]
