# Generated by Django 4.1.4 on 2023-01-10 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_data_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(140)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='data',
            name='hypotonic_urine',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='polyuria',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='serum_osmolality',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='serum_sodium',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
    ]
