# Generated by Django 4.1.5 on 2023-01-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('polyuria', models.PositiveIntegerField(null=True)),
                ('hypotonic_urine', models.FloatField(null=True)),
                ('thirst', models.PositiveIntegerField(choices=[(0, 'absent to low'), (1, 'excessive')], null=True)),
                ('serum_osmolality', models.PositiveIntegerField(null=True)),
                ('serum_sodium', models.PositiveIntegerField(null=True)),
                ('diagnosis', models.CharField(blank=True, choices=[(0, 'osmotic diuresis'), (1, 'fluid overload'), (2, 'diabetes insipidus'), (3, 'adipsic diabetes insipidus'), (4, 'healthy')], max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
