# Generated by Django 4.1.5 on 2023-01-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='diagnosis',
            field=models.CharField(blank=True, choices=[('0', 'osmotic diuresis'), ('1', 'fluid overload'), ('2', 'diabetes insipidus'), ('3', 'adipsic diabetes insipidus'), ('4', 'healthy')], max_length=30),
        ),
        migrations.AlterField(
            model_name='data',
            name='thirst',
            field=models.CharField(choices=[('absent to low', 'Absent to Low'), ('excessive', 'Excessive')], max_length=30, null=True),
        ),
    ]
