# Generated by Django 4.1.5 on 2023-01-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_data_diagnosis_alter_data_thirst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='thirst',
            field=models.PositiveIntegerField(choices=[(0, 'absent to low'), (1, 'Excessive')], null=True),
        ),
    ]
