# Generated by Django 4.1.5 on 2023-01-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_data_diagnosis_alter_data_thirst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
