# Generated by Django 4.1.7 on 2023-06-15 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_data_age_alter_data_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('pregnancies', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('glucose', models.PositiveIntegerField(null=True)),
                ('blood_pressure', models.PositiveIntegerField(null=True)),
                ('skin_thickness', models.PositiveIntegerField(null=True)),
                ('insulin', models.PositiveIntegerField(null=True)),
                ('bmi', models.FloatField(null=True)),
                ('diabetes_pedigree_function', models.FloatField(null=True)),
                ('age', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('outcome', models.CharField(blank=True, choices=[('0', 'Healthy'), ('1', 'Diabetes')], max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
