# Generated by Django 4.1.6 on 2023-06-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_diabetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
