# Generated by Django 4.1.6 on 2023-06-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_diabetes_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
