# Generated by Django 4.1.6 on 2023-06-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_data_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
