# Generated by Django 4.1.6 on 2023-06-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_data_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='rejected',
        ),
    ]
