# Generated by Django 4.1.6 on 2023-06-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_remove_data_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='outcome',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
